Version 0.5:     * Bugfixes:         - Fix negated srcport/dstport argument         - runtests supports trying rulesets (dangerous)         - testsuite fixes to allow trying

diff --git a/runtests b/runtests
--- a/runtests
+++ b/runtests
@@ -20,11 +20,22 @@ unset LC_MONETARY LC_NAME LC_NUMERIC LC_PAPER LC_TELEPHONE LC_TIME
 
 export FIREWALLY_SIMPLE_ERRORS=1
 
+T=`mktemp -d -t fwy.XXXXXX` || {
+    echo >&2 "cannot create temporary directory"
+    exit 1
+}
+[ -z "$T" -o "$T" = / ] && {
+    echo >&2 "cannot create temporary directory"
+    exit 1
+}
+trap "rm -rf $T" EXIT
+
+
 firewally()
 {
-    command ./firewally debug /dev/stdin >_tmp_out.$$
+    command ./firewally debug /dev/stdin >$T/tmp_out
     local res=$?
-    sed '/^#/d' <_tmp_out.$$
+    sed '/^#/d' <$T/tmp_out
     return $res
 }
 
@@ -40,17 +51,17 @@ failed()
     echo "  File:    $file"
     echo "  Command: $cmd"
     echo "  Standard output:"
-    sed 's/^/  | /' <_out.$$
+    sed 's/^/  | /' <$T/out
     echo "  Standard error:"
-    sed 's/^/  | /' <_err.$$
+    sed 's/^/  | /' <$T/err
     echo "  Reference output:"
-    sed 's/^/  | /' <_ref.$$
+    sed 's/^/  | /' <$T/ref
     if [ -n "$expect_error" ]; then
 	echo "  diff -u ref stderr:"
-	diff -u _ref.$$ _err.$$ | sed 's/^/  | /'
+	diff -u $T/ref $T/err | sed 's/^/  | /'
     else
 	echo "  diff -u ref stdout:"
-	diff -u _ref.$$ _out.$$ | sed 's/^/  | /'
+	diff -u $T/ref $T/out | sed 's/^/  | /'
     fi
     echo
     failed_tests=$[failed_tests + 1]
@@ -59,20 +70,28 @@ failed()
 run_test()
 {
     echo -n "$title: "
-    eval "$cmd" <_in.$$ >_out.$$ 2>_err.$$
+    eval "$cmd" <$T/in >$T/out 2>$T/err
     result="${PIPESTATUS[0]}"
     if [ -n "$expect_error" ]; then
 	if [ "$result" = 0 ]; then
 	    failed "expected error"
-	elif cmp -s _err.$$ _ref.$$; then
+	elif cmp -s $T/err $T/ref; then
 	    passed
 	else
 	    failed "error output differs"
 	fi
     else
 	if [ "$result" = 0 ]; then
-	    if cmp -s _out.$$ _ref.$$; then
-		passed
+	    if cmp -s $T/out $T/ref; then
+		if [ -n "$RUNTESTS_TRY" ]; then
+		    if iptables-restore < $T/out; then
+			passed
+		    else
+			failed
+		    fi
+		else
+		    passed
+		fi
 	    else
 		failed "output differs"
 	    fi
@@ -80,7 +99,7 @@ run_test()
 	    failed "got error"
 	fi
     fi
-    rm -f _out.$$ _err.$$
+    rm -f $T/out $T/err
     num_tests=$[num_tests + 1]
     title= expect_error=
 }
@@ -96,8 +115,8 @@ for file in tests/*; do
 	case "$line" in
 	    "TEST "*)
 		[ -n "$title" ] && run_test
-		: >_ref.$$
-		: >_in.$$
+		: >$T/ref
+		: >$T/in
 		title="${line#TEST }"
 		expect_error=
 		read cmd
@@ -106,11 +125,11 @@ for file in tests/*; do
 		expect_error=1
 		;;
 	    EOF)
-		mv -f _ref.$$ _in.$$
-		: >_ref.$$
+		mv -f $T/ref $T/in
+		: >$T/ref
 		;;
 	    *)
-		echo "$line" >> _ref.$$
+		echo "$line" >> $T/ref
 		;;
 	esac
     done < "$file"
@@ -118,7 +137,6 @@ for file in tests/*; do
 done
 
 echo "$num_tests tests: $passed_tests passed, $failed_tests failed"
-rm -f _in.$$ _out.$$ _err.$$ _ref.$$ _tmp_out.$$
 
 if [ "$failed_tests" -gt 0 ]; then
     exit 1
